---
- hosts: web
  become: true
  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=no state=latest

    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present
      notify:
         - restart apache2

    - name: stop service
      service: name=apache2 state=stopped

    - name: remove apache2
      apt: name=apache2 state=absent

    - name: Remove dependencies that are no longer required
      apt:
         autoremove: yes

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
